language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
services: mongodb
before_script:
  # MongoDB does not immediately accept connections: https://docs.travis-ci.com/user/database-setup/#mongodb
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"test",pwd:"test1234",roles:["readWrite"]});'
script: python -m unittest discover
